language: php

php:
  - 5.4

before_install:
  # apt-get installs
  - sudo apt-get update &> /dev/null
  - sudo apt-get install -y apache2 &> /dev/null

  # configure apache : tip from https://gist.github.com/3123962
  - sudo a2enmod actions &> /dev/null
  - sudo a2enmod rewrite &> /dev/null
  - sudo a2enmod headers &> /dev/null
  - echo "ServerName localhost" | sudo tee -a /etc/apache2/httpd.conf &> /dev/null
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars &> /dev/null
  - cat .travis/phpconfig | sudo tee /etc/apache2/conf.d/phpconfig &> /dev/null
  - cat .travis/virtualhost | sed -e "s~PATH~`pwd`~g" | sudo tee /etc/apache2/sites-available/default &> /dev/null

  # restart apache
  - sudo service apache2 restart &> /dev/null

before_script:
  # composer
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --optimize-autoloader --no-interaction

script:
  - phpunit --stop-on-failure

after_failure:
  - sudo cat /var/log/apache2/error.log

